apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  serviceName: "hdfs-namenode"
  replicas: 1
  selector:
    matchLabels:
      name: hdfs-namenode
  template:
    metadata:
      labels:
        name: hdfs-namenode
    spec:
      containers:
      - name: hdfs-namenode
        image: 172.20.101.40:6000/jinbozi/hdfs:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9000
          - containerPort: 8032
          - containerPort: 8088
          - containerPort: 50070
          - containerPort: 31822
        securityContext:
          privileged: true
        env:
          - name: image_function
            value: "namenode|resourcemanager"

